apiVersion: batch/v1
kind: Job
metadata:
  name: train-iris-gb-classifier
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: trainer
          image: training-job:latest
          imagePullPolicy: Never
          args: ["--config", "configs/iris_gb_classifier.json"]
          env:
            - name: MLFLOW_TRACKING_URI
              value: "http://host.docker.internal:5000"
            - name: PYTHONUNBUFFERED
              value: "1"
          volumeMounts:
            - name: configs
              mountPath: /app/configs
              readOnly: true
            - name: data
              mountPath: /app/.data
              readOnly: true
            - name: models
              mountPath: /app/.models
      volumes:
        - name: configs
          configMap:
            name: training-configs
        - name: data
          persistentVolumeClaim:
            claimName: training-data
        - name: models
          persistentVolumeClaim:
            claimName: training-models
