apiVersion: batch/v1
kind: Job
metadata:
  name: iris-training
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: trainer
          image: ml-project-template:latest
          imagePullPolicy: Never
          args: ["--config", "configs/iris_gb.json"]
          env:
            - name: MLFLOW_TRACKING_URI
              value: "http://host.docker.internal:5000"
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: GIT_PYTHON_REFRESH
              value: "quiet"
          volumeMounts:
            - name: data
              mountPath: /app/.data
              readOnly: true
            - name: models
              mountPath: /app/.models
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: training-data
        - name: models
          persistentVolumeClaim:
            claimName: training-models
